### PR TITLE
Extra image pipeline for adaptive sampling

### PR DESCRIPTION
**Pull request by Alpistinho**
Hi,

This is for conditionally adding an extra image pipeline in case the adaptive sampler is used.
Might cause some issues with the Blender color pipeline, in the sense that some regions might be under/oversampler due to a mismatch between what the sampler "sees" and what is shown in Blender.

This is, however, already the case and I would expect that Gamma correcting it would bring it closer than the current solution

The part that I implemented the conditional for changing the image pipeline index is a bit spaghetty, so let me know if you have a better solution

### CODE REVIEW

**Comment by Alpistinho** [comment]
The filesaver is currently exporting this new image pipeline with two gamma corrections in series, which will probably break the adaptive sampling when being used LuxcoreUI or the network rendering.

I can try to find a fix for it tomorrow before this is merged, but I always have the feeling that I am just adding workarounds to this code

**Comment by Theverat** [comment]
Thanks, great stuff.
There are some minor issues that I'll fix after merge.
About filesaver, is this extra imagepipeline even needed when rendering with standalone LuxCore?

**Comment by Theverat** [comment]
Fixes here: https://github.com/LuxCoreRender/BlendLuxCore/commit/39455013bee88379734d69053d2407fab62a861d

**Comment by Theverat** [comment]
Ok. I guess if `film.noiseestimation.index` is not set, it just uses the first imagepipeline?
If that's the case, I would just add a check to skip the creation of the noise-detection pipeline if filesaver is enabled.

**Pull request merged**
