### PR TITLE
 Odilkhan Yakubov Patchs for 4.0

### PR DESCRIPTION
**Pull request by odil24**
Copy of patchs for 4.0 branch

### CODE REVIEW

**Comment by odil24** [comment]
@Dade916 @neo2068 Please, review my commits

**Comment by wizard3376** [comment]
I can't install LuxCore

I downloaded the file with the new version of LuxCore, @neo2068 gave the link, here it is

https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4

but there is an error

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4\__init__.py", line 66, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.
You probably forgot to install one of the redistributable packages.
They are listed in the release announcement post.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore-for_blender_4.bin' (C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4\bin\__init__.py)


the error indicates a problem importing the pyluxcore module into Blender. Error "Failed to import pyluxcore

What to do? 0__0

**Comment by neo2068** [comment]
@odil24  The fixes for the node sockets doesn't work in this PR. Disabled nodes cannot be accessed by the brackets operator in the new blender api and there is a key not found error.
Do you have a duration comparison for the 'improved camera speed' and 'improved hair export' patch?

**Comment by wizard3376** [comment]
I tried to install the new LuxCore from the link 

https://github.com/LuxCoreRender/BlendLuxCore/tree/for_blender_4

but got the same error.

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
mod = importlib.import_module(module_name)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\BlendLuxCore-for_blender_4_init.py", line 66, in
raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception:

Maybe I'm doing something wrong?            0<_0?

**Comment by wizard3376** [comment]
@odil24 By the way, the camera is fast,
I haven't checked hair export yet

**Comment by odil24** [comment]
> @odil24 The fixes for the node sockets doesn't work in this PR. Disabled nodes cannot be accessed by the brackets operator in the new blender api and there is a key not found error. Do you have a duration comparison for the 'improved camera speed' and 'improved hair export' patch?

Can you explain which codes does not worked?

**Comment by neo2068** [comment]
For example this:
```
def update_use_ior(self, context):
   ior_input = self.inputs.get("LuxCoreSocketIOR")
   if ior_input:
      ior_input.enabled = self.use_ior
   specular_color_input = self.inputs.get("Specular Color")
   if specular_color_input:
      specular_color_input.enabled = not self.use_ior
   utils_node.force_viewport_update(self, context)
```

self.inputs.get("LuxCoreSocketIOR") returns NoneType for me. It only works with the name of the socket and when the socket is enabled. For disabled sockets I have to use the find method, e.g. self.inputs.get("IOR") and it returns the input id of the socket.

**Pull request closed without merging**
