### PR TITLE
Render rework2020

### PR DESCRIPTION
**Pull request by u3dreal**
added presets in lux renderpanel and in Lux camera settings image pipeline.

added fix for denoise not having x rights.

### CODE REVIEW

**Comment by Theverat** [comment]
**a)**
The view settings panel UI is a bit chaotic in my opinion:

view_settings

It might be a good idea to remove the final render related settings completely here (refresh interval and the refresh button), they are available in the image editor panel after all.
Then the panel could be renamed to "Viewport Render".
(as a side note, don't put "Settings" in any name here, all of these panels show settings)

**b)**
In Cycles, the preset effect is limited to the panel with the preset button. On the other hand, in the system proposed here, the preset button in the "light paths
I don't like that as a user, I have no indication which settings will be touched by a preset and which won't. 
We need some way to show this information to the user.

**Comment by Theverat** [comment]
**a)**
The view settings panel UI is a bit chaotic in my opinion:

view_settings

It might be a good idea to remove the final render related settings completely here (refresh interval and the refresh button), they are available in the image editor panel after all.
Then the panel could be renamed to "Viewport Render".
(as a side note, don't put "Settings" in any name here, all of these panels show settings)

**b)**
In Cycles, the preset effect is limited to the panel with the preset button. On the other hand, in the system proposed here, the preset button in the "Light Paths" panel affects many settings that are in other panels.

I don't like that, as a user, I have no indication which settings will be touched by a preset and which won't. 
We need some way to show this information to the user, for example with a tooltip listing all the affected settings and what their values will be set to.

**c)**
A system to create and maintain pre-configured presets is missing.
If we continue to use the Blender presets system, we should check on addon registration if the BlendLuxCore preset folder exists, and if not, create it and copy over the default presets.

**d)**
I'm still not totally convinced if it's a good idea to use the Blender preset system.
Letting users create their own presets can create a versioning nightmare for us in the future.
What if we update one of the "official" pre-configured presets, but the users has modified their preset file? How do we detect this, do we overwrite it or make a copy, etc.?
It creates a huge host of problems.

To be honest, I would prefer it to just have pre-configured presets in the addon, which are available from a simple menu that we fully control.
Power users could still modify the addon source code to create own presets or modify existing ones, but it would be clear that the burden of versioning is on them if they do so.

What are your thoughts on this?

**Comment by u3dreal** [comment]
a) I totally agree. removed display settings from Viewport Render menu.
 Anyway i did not know this great LuxCore panel exists in the image editor.
I would suggest to open it by default. Looks really pro.

b) is this still necessary now that users can not create presets in rendersettings ?

c) done .. Blendluxcore now checks for preset folder and copies supplied defaults if necessary
We might have to add stuff here so we can update the presets if necessary.

d) Good idea . now users can not add or remove presets for sampling presets. code is just commented out so powerusers can create presets.

I'm still unsure what to do with the image pipeline .. 
As an artist i would like to be able to put together my own "looks" for luxcore ... so maybe i would be a good idea to let them make presets for the whole image pipeline.
Since values that no more exist are ignored from the execute_preset function that would not hurt too much. And we could state that this is at their own risk :) I would also not provide default presets here.or maybe we could ...

Another idea was maybe to put the image pipeline into the image editor panel ... so one could tweak the imagepipeline there during render. When using an extra window for rendering you have to switch windows all the time to tweak the imagepipeline. 

And have there been thoughts on being able to weak the image pipeline after rendering ??

**Comment by u3dreal** [comment]
Now using symlinks so updating will be easy.

**Comment by Theverat** [comment]
> b) is this still necessary now that users can not create presets in render settings ?

Yes, I think so.

> c) done .. Blendluxcore now checks for preset folder and copies supplied defaults if necessary
We might have to add stuff here so we can update the presets if necessary.
Maybe just symlink to BlendLuxCore/presets ? edit: Done

To be honest, for non-editable presets I would not bother with the Blender preset system at all, it just adds needless complication. 
It would be better to just have one menu with a few preset entries, then an operator that is executed which applies the preset (there could be a different function for each preset, if it makes sense).
This way we have full control and less complexity.

As a side note, I think symlinking in the addons or presets folders is a bad idea, it could have the craziest effects in the future. So I would remove that.

> I'm still unsure what to do with the image pipeline ..
As an artist i would like to be able to put together my own "looks" for luxcore ... so maybe i would be a good idea to let them make presets for the whole image pipeline.
Since values that no more exist are ignored from the execute_preset function that would not hurt too much. And we could state that this is at their own risk :) I would also not provide default presets here.or maybe we could ...
We could omit this for now and decide later ..

I would do this as a separate pull request. 
One of the reasons I'm taking so long to review this pull request is that you have too much stuff mingled into one: 
- render settings UI rework
- render presets (with potential versioning trouble)
- image pipeline presets

It would be easier if you would do these steps one after the other, creating a pull request for each one that are not interconnected. (of course, the second point can only be done after the first)

> Another idea was maybe to put the image pipeline into the image editor panel ... so one could tweak the imagepipeline there during render. When using an extra window for rendering you have to switch windows all the time to tweak the imagepipeline.

I had something similar in the old LuxBlend, this is certainly doable (and probably not even much work). You can probably just call the same draw code as in the imagepipeline panel.

> And have there been thoughts on being able to weak the image pipeline after rendering ??

This would require a lot of work (I think). We would have to save a LuxCore film file and load it back, then edit the imagepipelines in there and retrieve the result).

**Comment by u3dreal** [comment]
I made this request for the ui fixing only now. And the fix for x rights on osx .. or is this also relevant for linux / Windows. I understand your nitpicking because it is your baby.
Otherwise i would not have asked you. :) But the preset thing was your idea :).
Never mind ....

**Pull request merged**
