### PR TITLE
Add MacOS pyluxcoretools Network Render support

### LINKED ISSUE #222: Mac OS support missing in pyluxcoretools button operator
We need to add Mac OS support here:
https://github.com/LuxCoreRender/BlendLuxCore/blob/master/operators/pyluxcoretools.py#L90
(This operator is called when the user clicks on the "Network Render" button)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64750627-mac-os-support-missing-in-pyluxcoretools-button-operator?utm_campaign=plugin&utm_content=tracker%2F80143047&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F80143047&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rebpdx**
This pull request adds MacOS support for the Network Render button.

Please test on Windows and Linux as I don't have a GUI Linux or Windows system available. The my_env variable should not change the behavior.

**Needed Wiki info:** I don't have access to wiki as far as I know but some instructions for install should be added to match error output in this PR.

-----------------
**Note for MacOS users**: python3, pip3 and PySide2 need to be installed
The plugin assumes python3 is available from /usr/local/bin or /usr/local/sbin if you have an unusual install you can add symbolic links. If you don't have Python3 installed the easiest method is:

```
brew install python3
brew install pip3
pip3 install PySide2
```

If you're using pyenv and also have a brew install you may need to do

```
/usr/local/bin/pip3 isntall PySide2
```
-----------------

Fixes #222

### CODE REVIEW

**Comment by Theverat** [comment]
Thank you :)
I have asked Dade to create a wiki account for you, unfortunately we had to close the registration because there were some spambots.

**Comment by rebpdx** [comment]
No worries, those spambots definitely make things more difficult.

**Comment by Theverat** [comment]
By the way, I created a section about Mac OS installation on this wiki page:
https://wiki.luxcorerender.org/LuxCoreRender_Network_Rendering
It is now opened from a error popup in blender if python3 or pyside is not installed.

**Comment by rebpdx** [comment]
Thank you, I had thought about doing the web browser open but my implementation was flashing the popup faster than a human could read before blender lost focus on the web browser. One of these days my BlenderUI skills will be better...

It looks like I now have wiki access, so should be able to provide better instructions now.

**Pull request merged**
